name: DVC setup
on: 
  push:
    branches:
      main
    paths:
      - data/*

jobs:
  run_code:
    name: Run DVC pull
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      
